services:
  - type: web
    name: card-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run dev
    envVars:
      - key: NODE_VERSION
        value: 18
    staticPublishPath: public
